### ISSUE TITLE
Unexpected results in openbmc-tof-election-data

### ISSUE THREAD

**Issue by zevweiss** [openbmc/technical-oversight-forum#10]
Re: [@williamspatrick's email](https://lore.kernel.org/openbmc/YeH2OHImO%2FoRgkjN@heinlein/), I'm a bit confused at the results I see for my own contributions in the election-data repo.  From what I see [here](https://github.com/williamspatrick/openbmc-tof-election-data/blob/28cc15a3f5cfe2ac8bba094a61e97277e3546961/2021H2/data/commits.txt#L1634), it looks like the only commit of mine that got counted was [this](https://gerrit.openbmc-project.xyz/c/openbmc/x86-power-control/+/46589) (which I wouldn't have expected to cross the threshold of non-triviality), whereas other more significant patches I've contributed don't seem to have been picked up:

 - https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/44463
 - https://gerrit.openbmc-project.xyz/c/openbmc/x86-power-control/+/46584
 - https://gerrit.openbmc-project.xyz/c/openbmc/x86-power-control/+/46585
 - https://gerrit.openbmc-project.xyz/c/openbmc/x86-power-control/+/46586

In combination with various other bits and pieces (assorted OpenBMC-related kernel patches and Discord support, etc.) I had been expecting that my contributions would be sufficient to qualify me for the "active" tier, and would appreciate it if the automated determination could be reconsidered.

**Comment by edtanous** [comment]
The scripts that were used to generate this information are all published as part of #8.  Could you look at your specific patches when run through that script and determine why they weren't counted?  It's highly probable that we did something unintentional here, but without anyone having gone through your specific case, it's hard to say if this is a script issue or a policy issue.  For the moment, discord support isn't counted, and that might be difficult to setup given that discord history is time bounded, we don't have a complete history to base something off, but if you found a way to improve the tool to make it happen, I would be all for it.  In regards to linux kernel patches, again, I suspect that we don't have a good way to differentiate "openbmc relevant" patches in the script, but if there's a way I'd be for getting it added.

Also, FWIW, because the TOF repo is for voting, and this bug isn't asking for a vote, I wonder if we should reopen this bug under openbmc/openbmc-tools, considering that's essentially what you're asking about.

**Comment by zevweiss** [comment]
It looks like the scripts involved haven't yet been merged into openbmc-tools; if we're diving into specific script bugs, I guess I should just comment on the still-open gerrit reviews then...

**Comment by zevweiss** [comment]
Gerrit discussion opened [here](https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/50179/2#message-a6ee0b97efd9642595f7e7013a26c82050cda3b9).

**Comment by williamspatrick** [comment]
I have fixed the issue and reopened #9 for a revote with the new data.  You are now tentatively qualified.

Thank you much for identifying this problem and finding the solution.  We have increased the number of developers who have qualified by quite a bit!
