### ISSUE TITLE
proposal: move forward with `lg2` as new logging API

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/technical-oversight-forum#3]
See https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/45310

**Comment by williamspatrick** [comment]
"move forward" means accept `lg2` as a "better" API.  It does not mean force all code to start using it and/or phosphor-logging.

**Comment by williamspatrick** [comment]
1. This is not being mandated.
2. The TOF has no disagreement, as a direction, with going forward over the existing phosphor-logging APIs.

The maintainer(s) and author will work through anything else offline.

**Comment by edtanous** [comment]
To add context to my vote, and reinforce what @williamspatrick said, this is not to convey that this is approved, and mandated to be used everywhere.  This vote is to say that this discussion and development can continue.  From my perspective, there are still a lot of questions about "why is structured logging useful?", "Should we be inventing our own API?" and "Should we use the journal?" but since we already have structured logging, and this is simply a better API to the existing feature, this vote isn't intending to answer any of those questions.
