### ISSUE TITLE
OpenBMC inventory architecture

### ISSUE THREAD

**Issue by alatarum** [openbmc/technical-oversight-forum#6]

**Comment by alatarum** [comment]
Lore: not sent yet
Gerrit: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/49493

**Comment by edtanous** [comment]
Left lots of details in the doc, but as a theme, there's not enough actionable information in the proposal, and the proposal is still on patchset 1.  Given the desire for timely responses, and it's already been a month since proposing, I'm going to vote no for the moment, although I suspect there is a much shorter doc that I would be able to vote positively for.

**Comment by williamspatrick** [comment]
Closing for now due to inaction.
